services:
  app:
    container_name: app-e-dziennik
    image: app-e-dziennik
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diary_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "diary_db", "-h", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 10
  redis:
    image: redis
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6379:6379"
