ALTER SEQUENCE grade_id_seq RESTART WITH 1;
ALTER SEQUENCE role_id_seq RESTART WITH 1;
ALTER SEQUENCE student_id_seq RESTART WITH 1;
ALTER SEQUENCE teacher_id_seq RESTART WITH 1;
ALTER SEQUENCE school_class_id_seq RESTART WITH 1;
ALTER SEQUENCE subject_id_seq RESTART WITH 1;
ALTER SEQUENCE student_subject_id_seq RESTART WITH 1;
ALTER SEQUENCE school_level_id_seq RESTART WITH 1;
ALTER SEQUENCE school_id_seq RESTART WITH 1;

