ALTER SEQUENCE grade_id_seq RESTART WITH 1;
ALTER SEQUENCE role_id_seq RESTART WITH 1;
ALTER SEQUENCE student_id_seq RESTART WITH 1;
ALTER SEQUENCE teacher_id_seq RESTART WITH 1;
ALTER SEQUENCE school_class_id_seq RESTART WITH 1;
ALTER SEQUENCE subject_id_seq RESTART WITH 1;
ALTER SEQUENCE student_subject_id_seq RESTART WITH 1;
ALTER SEQUENCE school_level_id_seq RESTART WITH 1;
ALTER SEQUENCE school_id_seq RESTART WITH 1;
-- DELETE FROM student_subject;
-- DELETE FROM subject;
-- DELETE FROM STUDENT;
-- DELETE FROM teacher;
-- DELETE FROM school_class;
-- DELETE FROM school;
-- DELETE FROM school_level;
-- DELETE FROM person_information;
-- DELETE FROM address;
-- DELETE FROM users;
-- DELETE FROM role;
-- DELETE FROM app_settings;
