spring:
  sql:
    init:
      mode: embedded
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    mapping-resources:
      /mappings/TeacherDao.hbm.xml,
      /mappings/RoleDao.hbm.xml,
      /mappings/StudentDao.hbm.xml,
      /mappings/StudentSubjectDao.hbm.xml,
      /mappings/SchoolClassDao.hbm.xml,
      /mappings/SubjectDao.hbm.xml,
      /mappings/PersonInformationDao.hbm.xml,
      /mappings/SchoolDao.hbm.xml,
      /mappings/AdminDao.hbm.xml,
      /mappings/UserDao.hbm.xml,
      /mappings/SettingsDao.hbm.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/diary_db
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:liquibase-changeLog.xml


jwt:
  secret: testtt
  expiration: 3600000
  refresh:
    expiration: 4800000
  token:
    prefix: Bearer