spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    mapping-resources:
      /mappings/TeacherDao.hbm.xml,
      /mappings/RoleDao.hbm.xml,
      /mappings/StudentDao.hbm.xml,
      /mappings/StudentSubjectDao.hbm.xml,
      /mappings/SchoolClassDao.hbm.xml,
      /mappings/SubjectDao.hbm.xml,
      /mappings/PersonInformationDao.hbm.xml,
      /mappings/SchoolDao.hbm.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/diary_db
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:liquibase-changeLog.xml

jwt:
  secret: testtt
  expiration: 3600000
  refresh:
    expiration: 4800000
  token:
    prefix: Bearer
  unauthorized:
    message: You are not logged in !
  accessDenied:
    message: You do not have access to this site !
  authFailure:
    message: Wrong username or password !