spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false
    mapping-resources:
      /mappings/TeacherDao.hbm.xml,
      /mappings/RoleDao.hbm.xml,
      /mappings/StudentDao.hbm.xml,
      /mappings/StudentSubjectDao.hbm.xml,
      /mappings/SchoolClassDao.hbm.xml,
      /mappings/SubjectDao.hbm.xml,
      /mappings/PersonInformationDao.hbm.xml,
      /mappings/SchoolDao.hbm.xml,
      /mappings/AdminDao.hbm.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/diary_db
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:liquibase-changeLog.xml

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: info

jwt:
  secret: testtt
  expiration: 3600000
  refresh:
    expiration: 4800000
  token:
    prefix: Bearer