server:
  port: 8100
spring:
  profiles:
    default: dev
  sql:
    init:
      mode: embedded
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
    redis:
      time-to-live: 5000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase-changeLog.xml



logging:
  level:
    pl.edziennik.application: DEBUG
    org:
      springframework:
        web: DEBUG



#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

#logging:
#  level:
#    root: DEBUG

schoolclass:
  config:
    maxStudentsSize: 30
    autoAssignSubjects: true

school:
  config:
    averageType: ARITHMETIC
    maxLessonTime: 45
    minScheduleTime: 10

jwt:
  secret: testtt
  expiration: 3600000
  refresh:
    expiration: 122
  token:
    prefix: Bearer

application:
  address: localhost:8080/

groovy:
  execution:
    timeout: 10
